/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.event.*;

/**
 *
 * @author Manuel Jesús Grávalos Cano, Francisco Jesús Beltrán Moreno
 */
public class Menu extends javax.swing.JFrame {
    private Proyecto_LSystem p;
    /**
     * Creates new form Menu
     */
    public Menu(Proyecto_LSystem p) {
        this.p = p;
        this.setSize(640,370);
        this.setLocation(p.getWidth()+600, p.getHeigth()-450);
        initComponents();
        advertencia.setVisible(false);
        advertencia2.setVisible(false);
        iteraciones.addChangeListener(new ChangeListener(){
                    public void stateChanged(ChangeEvent e){
                        Integer i = iteraciones.getValue();
                        if (i >= 5){
                            advertencia.setVisible(true);
                            advertencia2.setVisible(true);
                        }
                        else{
                            advertencia.setVisible(false);
                            advertencia2.setVisible(false);
                        }
                    }
                });

    }
    public int getIteraciones(){
        return iteraciones.getValue();
    }
    
    public int getAngulo(){
        return expansion.getValue();
    }
    
    public int getExtensionRama(){
        return ramas.getValue();
    }
    public int getExtensionChaos(){
        return ext_chaos.getValue();
    }
    
    public int getAnguloChaos(){
        return ang_chaos.getValue();
    }
    
    public int[] getDatos(){
        int[] i = {getIteraciones(),getAngulo(),getExtensionRama(),getAnguloChaos(),getExtensionChaos()};
        return i;
    }
    
    public String getLsystem(){
        return lsystem.getSelectedItem().toString();
    }
    public String getFichero(){
        String ruta = new String();
        ruta += documento.getText() + ext.getSelectedItem().toString();
        return ruta;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iteraciones = new javax.swing.JSlider();
        expansion = new javax.swing.JSlider();
        ramas = new javax.swing.JSlider();
        lsystem = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        advertencia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        ext = new javax.swing.JComboBox();
        advertencia2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ang_chaos = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        ext_chaos = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Numero de iteraciones (n)");

        jLabel2.setText("Ángulo de expansión (grados)");

        jLabel3.setText("Extensión de las ramas (unidades)");

        iteraciones.setMajorTickSpacing(1);
        iteraciones.setMaximum(10);
        iteraciones.setMinimum(3);
        iteraciones.setPaintLabels(true);
        iteraciones.setPaintTicks(true);
        iteraciones.setSnapToTicks(true);
        iteraciones.setValue(3);

        expansion.setMajorTickSpacing(15);
        expansion.setMaximum(180);
        expansion.setMinimum(15);
        expansion.setPaintLabels(true);
        expansion.setPaintTicks(true);
        expansion.setDoubleBuffered(true);

        ramas.setMajorTickSpacing(1);
        ramas.setMaximum(20);
        ramas.setMinimum(10);
        ramas.setPaintLabels(true);
        ramas.setPaintTicks(true);

        lsystem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F[+F]F[-F]", "F[-F]F[+F]", "FF[-F][-F][+F][-F][+F]", "FF[+F][-F][-F][-F][+F]" ,"F[+F]F[-F]F[-F]F[+F]", "F[-F]F[+F]F[-F]F[+F]F[-F]F[+F]" }));

        jLabel4.setText("L-System");

        jButton1.setText("GENERAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        advertencia.setForeground(new java.awt.Color(225, 0, 0));
        advertencia.setText("Si el número de iteraciones es superior a 4");

        jLabel5.setText("Captura de pantalla (PULSE C):");

        documento.setText("nombre_fichero_salida");

        ext.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".jpg", ".png", ".tif", ".bmp" }));

        advertencia2.setForeground(new java.awt.Color(225, 0, 0));
        advertencia2.setText("el programa podría ralentizar su dispositivo");

        jLabel7.setText("Entropía del ángulo de expansión [0,1]");

        ang_chaos.setMajorTickSpacing(1);
        ang_chaos.setMaximum(10);
        ang_chaos.setPaintLabels(true);
        ang_chaos.setPaintTicks(true);
        ang_chaos.setValue(5);

        jLabel8.setText("Entropía de la extensión de las ramas [0,1]");

        ext_chaos.setMajorTickSpacing(1);
        ext_chaos.setMaximum(10);
        ext_chaos.setPaintLabels(true);
        ext_chaos.setPaintTicks(true);
        ext_chaos.setValue(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lsystem, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(ext_chaos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(advertencia)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(advertencia2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expansion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ramas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ang_chaos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lsystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iteraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(expansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ramas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ang_chaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ext_chaos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(advertencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advertencia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        p.actualiza(this.getDatos(),this.getLsystem(),this.getFichero());
    }                                        
 

    // Variables declaration - do not modify                     
    private javax.swing.JLabel advertencia;
    private javax.swing.JLabel advertencia2;
    private javax.swing.JSlider ang_chaos;
    private javax.swing.JTextField documento;
    private javax.swing.JSlider expansion;
    private javax.swing.JComboBox<String> ext;
    private javax.swing.JSlider ext_chaos;
    private javax.swing.JSlider iteraciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> lsystem;
    private javax.swing.JSlider ramas;
    // End of variables declaration                   
}
